### ISSUE TITLE
Doesn't convert automatically

### ISSUE THREAD

**Issue by vbwx** [tyrone-sudeium/st3-binaryplist#3]
This plugin always worked like a charm for me, but now – perhaps after a Sublime update – binary plist files are displayed in a hexadecimal encoding again.

I already tried to debug this problem, and I found that the expression `view.substr(Region(0,19)) == '6270 6c69 7374 3030'` returns `True`, so that should work, and calling `view.run_command('binary_plist_toggle')` directly does convert the file as expected, strangely enough.

Could there be a conflict with another plugin?

**Comment by vbwx** [comment]
Just found out something else: Opening a bplist file for the first time yields a hexadecimal representation (and sometimes even some binary mess), then after closing and opening it again, the plugin works its magic and I see an XML plist. Then it works for all plist files, until I quit Sublime!

I guess this problem might not have anything to do with this plugin.

**Comment by wurensen** [comment]
> Just found out something else: Opening a bplist file for the first time yields a hexadecimal representation (and sometimes even some binary mess), then after closing and opening it again, the plugin works its magic and I see an XML plist. Then it works for all plist files, until I quit Sublime!
> 
> I guess this problem might not have anything to do with this plugin.

It work wrong first time when I open a plist file.
